const EQUIPMENT_ITEMS = [
  // Napierśnik (obóz)
  {
    id: "zbroja_wyprawowa",
    name: "Zbroja Wyprawowa",
    slot: "napiersnik",
    icon: "🥋",
    vendor: "camp",
    description: "Lekki pancerz łowców Gildii, zszywany ze skóry aberracji.",
    bonus: { pancerz: 0.04 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "kolczuga_kopalniana",
    name: "Kolczuga Kopalniana",
    slot: "napiersnik",
    icon: "⛓️",
    vendor: "camp",
    description: "Wykuta przez Gildię Rzemieślników z rudy odpornej na spaczenie many.",
    bonus: { pancerz: 0.07 },
    cost: { currency: "Kryształy Esencji", amount: 12 },
  },
  {
    id: "plyta_krysztalowa",
    name: "Płyta Kryształowa",
    slot: "napiersnik",
    icon: "💠",
    vendor: "camp",
    description: "Pancerz inkrustowany esencją — ciężki, ale niemal nieprzebity.",
    bonus: { pancerz: 0.12 },
    cost: { currency: "Kryształy Esencji", amount: 25 },
  },
  // Naszyjnik (obóz)
  {
    id: "amulet_sily",
    name: "Amulet Siły",
    slot: "naszyjnik",
    icon: "💪",
    vendor: "camp",
    description: "Zaklęty przez Zakon Światła talizman wzmacniający ciało.",
    bonus: { str: 3 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "amulet_zrecznosci",
    name: "Amulet Zręczności",
    slot: "naszyjnik",
    icon: "🌀",
    vendor: "camp",
    description: "Wykonany ze spaczonych ziół, przyspiesza ruchy nosiciela.",
    bonus: { zre: 3 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "amulet_umyslu",
    name: "Amulet Umysłu",
    slot: "naszyjnik",
    icon: "🧠",
    vendor: "camp",
    description: "Kryształ esencji oszlifowany tak, by wzmacniać koncentrację.",
    bonus: { int: 3 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "talizman_przebicia",
    name: "Talizman Przebicia",
    slot: "naszyjnik",
    icon: "🗡️",
    vendor: "camp",
    description: "Nagroda za polowania dla Gildii — osłabia pancerz przeciwnika.",
    bonus: { przebicie: 0.06 },
    cost: { currency: "Kryształy Esencji", amount: 14 },
  },
  // Nowe sloty (obóz)
  {
    id: "kaptur_wedrowca",
    name: "Kaptur Wędrowca",
    slot: "helm",
    icon: "🧢",
    vendor: "camp",
    description: "Prosty kaptur noszony przez każdego, kto wyrusza poza mury.",
    bonus: { pancerz: 0.03 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "rekawice_skorzane",
    name: "Rękawice Skórzane",
    slot: "rekawice",
    icon: "🧤",
    vendor: "camp",
    description: "Wzmacniają chwyt i pewność ciosu.",
    bonus: { str: 2 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "spodnie_wedrowca",
    name: "Spodnie Wędrowca",
    slot: "spodnie",
    icon: "👖",
    vendor: "camp",
    description: "Wzmacniane w kolanach — nieocenione na długich wyprawach.",
    bonus: { pancerz: 0.03 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "buty_wedrowca",
    name: "Buty Wędrowca",
    slot: "buty",
    icon: "🥾",
    vendor: "camp",
    description: "Lekkie podeszwy, które nie zdradzają kroku.",
    bonus: { zre: 2 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "pierscien_mocy",
    name: "Pierścień Mocy",
    slot: "pierscien",
    icon: "💍",
    vendor: "camp",
    description: "Prosty pierścień z wygrawerowanym symbolem siły.",
    bonus: { str: 2 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "pierscien_zwinnosci",
    name: "Pierścień Zwinności",
    slot: "pierscien",
    icon: "💍",
    vendor: "camp",
    description: "Lekki jak piórko — prawie nie czuć go na palcu.",
    bonus: { zre: 2 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "podreczny_sztylet",
    name: "Podręczny Sztylet",
    slot: "prawa_reka",
    icon: "🗡️",
    vendor: "camp",
    description: "Prosty, dobrze wyważony sztylet — podstawowa broń każdego najemnika.",
    weapon: { name: "Podręczny Sztylet", minDmg: 6, maxDmg: 10, range: 1 },
    bonus: { przebicie: 0.03 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "noz_do_rzucania",
    name: "Nóż do Rzucania",
    slot: "lewa_reka",
    icon: "🔪",
    vendor: "camp",
    description: "Lekki, wyważony do rzutu — trzymany w wolnej dłoni na wszelki wypadek.",
    weapon: { name: "Nóż do Rzucania", minDmg: 5, maxDmg: 8, range: 3 },
    bonus: { zre: 2 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },

  // Kuźnia Gildii Rzemieślników
  {
    id: "plyty_gildyjne",
    name: "Płyty Gildyjne",
    slot: "napiersnik",
    icon: "🛡️",
    vendor: "kuznia",
    description: "Najlepsza robota Gildii Rzemieślników — pancerz wart fortuny, kuty na zamówienie samej Rady.",
    bonus: { pancerz: 0.15 },
    cost: { currency: "Kryształy Esencji", amount: 30 },
  },
  {
    id: "obrecz_kowalska",
    name: "Obręcz Kowalska",
    slot: "naszyjnik",
    icon: "⚙️",
    vendor: "kuznia",
    description: "Zaklęta przez kowali Gildii obręcz — hartuje ciało nosiciela jak stal w kuźni.",
    bonus: { wyt: 3 },
    cost: { currency: "Kryształy Esencji", amount: 16 },
  },
  {
    id: "helm_bojowy",
    name: "Hełm Bojowy",
    slot: "helm",
    icon: "⛑️",
    vendor: "kuznia",
    description: "Solidny hełm kuty z myślą o realnym starciu, nie tylko paradzie.",
    bonus: { pancerz: 0.06 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
  {
    id: "rekawice_kolczaste",
    name: "Rękawice Kolczaste",
    slot: "rekawice",
    icon: "🧤",
    vendor: "kuznia",
    description: "Kolce wzmacniające każde uderzenie w słaby punkt pancerza.",
    bonus: { przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 14 },
  },
  {
    id: "nogawice_plytowe",
    name: "Nogawice Płytowe",
    slot: "spodnie",
    icon: "👖",
    vendor: "kuznia",
    description: "Ciężkie płyty ochronne — spowalniają, ale chronią żywotne stawy.",
    bonus: { wyt: 3 },
    cost: { currency: "Kryształy Esencji", amount: 18 },
  },
  {
    id: "naramiennik_tarczowy",
    name: "Naramiennik Tarczowy",
    slot: "lewa_reka",
    icon: "🛡️",
    vendor: "kuznia",
    description: "Osłania przedramię przed ciosami, które nie trafiły w korpus.",
    bonus: { pancerz: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 16 },
  },
  {
    id: "naramiennik_uderzeniowy",
    name: "Naramiennik Uderzeniowy",
    slot: "prawa_reka",
    icon: "👊",
    vendor: "kuznia",
    description: "Wzmocniony staw łokciowy — każdy cios wychodzi mocniejszy.",
    bonus: { str: 3 },
    cost: { currency: "Kryształy Esencji", amount: 16 },
  },
  {
    id: "pierscien_hartu",
    name: "Pierścień Hartu",
    slot: "pierscien",
    icon: "💍",
    vendor: "kuznia",
    description: "Kuty w ogniu esencji — hartuje ciało tak jak stal.",
    bonus: { wyt: 2 },
    cost: { currency: "Kryształy Esencji", amount: 12 },
  },
  {
    id: "kuty_topor_boczny",
    name: "Kuty Topór Boczny",
    slot: "prawa_reka",
    icon: "🪓",
    vendor: "kuznia",
    description: "Solidna robota kowali Gildii — cięższy niż sztylet, ale mocniej rani.",
    weapon: { name: "Kuty Topór Boczny", minDmg: 9, maxDmg: 14, range: 1 },
    bonus: { str: 2 },
    cost: { currency: "Kryształy Esencji", amount: 18 },
  },
  {
    id: "parujacy_sztylet_gildii",
    name: "Parujący Sztylet Gildii",
    slot: "lewa_reka",
    icon: "⚔️",
    vendor: "kuznia",
    description: "Krótkie ostrze trzymane w wolnej dłoni, wyważone tak, by odbijać ciosy.",
    weapon: { name: "Parujący Sztylet", minDmg: 7, maxDmg: 11, range: 1 },
    bonus: { pancerz: 0.03 },
    cost: { currency: "Kryształy Esencji", amount: 16 },
  },

  // Świątynia Zakonu Światła
  {
    id: "szata_blogoslawiona",
    name: "Szata Błogosławiona",
    slot: "napiersnik",
    icon: "🧥",
    vendor: "swiatynia",
    description: "Tkanina nasączona światłem — chroni duszę niemal tak samo mocno jak ciało.",
    bonus: { pancerz: 0.05, cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 12 },
  },
  {
    id: "relikwiarz",
    name: "Relikwiarz",
    slot: "naszyjnik",
    icon: "🔔",
    vendor: "swiatynia",
    description: "Fragment relikwii Zakonu Światła — wzmacnia więź nosiciela z esencją.",
    bonus: { int: 3 },
    cost: { currency: "Kryształy Esencji", amount: 14 },
  },
  {
    id: "sandaly_pielgrzyma",
    name: "Sandały Pielgrzyma",
    slot: "buty",
    icon: "🩴",
    vendor: "swiatynia",
    description: "Noszone przez wędrownych kapłanów Zakonu — niewygodne, ale budzą zaufanie.",
    bonus: { cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "bransoleta_wiary",
    name: "Bransoleta Wiary",
    slot: "lewa_reka",
    icon: "📿",
    vendor: "swiatynia",
    description: "Sznur paciorków otulony słabym, ciepłym światłem.",
    bonus: { int: 2 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "bransoleta_swiatla",
    name: "Bransoleta Światła",
    slot: "prawa_reka",
    icon: "✨",
    vendor: "swiatynia",
    description: "Emanuje słabym blaskiem, który dodaje otuchy w walce.",
    bonus: { cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "pierscien_wiedzy",
    name: "Pierścień Wiedzy",
    slot: "pierscien",
    icon: "💍",
    vendor: "swiatynia",
    description: "Noszony niegdyś przez uczonego Zakonu — wciąż pulsuje słabą mądrością.",
    bonus: { int: 2 },
    cost: { currency: "Kryształy Esencji", amount: 12 },
  },
  {
    id: "swiety_sztylet_osadu",
    name: "Święty Sztylet Osądu",
    slot: "prawa_reka",
    icon: "🕯️",
    vendor: "swiatynia",
    description: "Poświęcone ostrze noszone przez egzekutorów wiary — osądza, zanim wysłucha.",
    weapon: { name: "Święty Sztylet Osądu", minDmg: 8, maxDmg: 12, range: 1 },
    bonus: { cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 14 },
  },
  {
    id: "kadzielnica_bojowa",
    name: "Kadzielnica Bojowa",
    slot: "lewa_reka",
    icon: "🪔",
    vendor: "swiatynia",
    description: "Rozżarzone kadzidło rzucane w twarz przeciwnika — bardziej broń niż ozdoba.",
    weapon: { name: "Kadzielnica Bojowa", minDmg: 6, maxDmg: 10, range: 3 },
    bonus: { int: 2 },
    cost: { currency: "Kryształy Esencji", amount: 14 },
  },

  // Czarny Rynek
  {
    id: "przemycony_pancerz",
    name: "Przemycony Pancerz Aberracji",
    slot: "napiersnik",
    icon: "🦴",
    vendor: "czarny_rynek",
    description: "Zszyty ze skóry aberracji, sprzedany przez kogoś, kto nie miał prawa go posiadać.",
    bonus: { pancerz: 0.09, przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 22 },
  },
  {
    id: "sygnet_rady",
    name: "Kradziony Sygnet Rady",
    slot: "pierscien",
    icon: "💍",
    vendor: "czarny_rynek",
    description: "Sygnet z herbem jednego z Radnych — ktoś zapłaci fortunę, żeby go odzyskać, ale na razie jest Twój.",
    bonus: { str: 2, cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
  {
    id: "zatruty_sztylet_przemytnika",
    name: "Zatruty Sztylet Przemytnika",
    slot: "prawa_reka",
    icon: "☠️",
    vendor: "czarny_rynek",
    description: "Ostrze nasączone trucizną nieznanego pochodzenia — przemytnicy nie zadają zbędnych pytań.",
    weapon: { name: "Zatruty Sztylet", minDmg: 9, maxDmg: 13, range: 1 },
    bonus: { przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 24 },
  },
  {
    id: "ukryty_noz_do_rzucania",
    name: "Ukryty Nóż do Rzucania",
    slot: "lewa_reka",
    icon: "🥷",
    vendor: "czarny_rynek",
    description: "Chowany w rękawie, niewidoczny dla oka strażnika — dopóki nie jest za późno.",
    weapon: { name: "Ukryty Nóż", minDmg: 6, maxDmg: 9, range: 4 },
    bonus: { zre: 2 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
  // Wytwory Kuźni — bez pola vendor (nigdy nie trafiają do zwykłych sklepów),
  // powstają wyłącznie przez wytwarzanie (main.js: craftItem) z surowców kilku
  // różnych lokacji naraz (patrz js/crafting.js). Pole cost tu nie jest ceną
  // zakupu — służy tylko jako wartość odsprzedaży/ulepszenia, takiej samej
  // jak przy zwykłym ekwipunku.
  {
    id: "medalion_dwoch_drog",
    name: "Medalion Dwóch Dróg",
    slot: "naszyjnik",
    icon: "💫",
    crafted: true,
    description: "Kryształ esencji oprawiony w spaczone zioła — dwie sprzeczne moce splecione w jeden amulet.",
    bonus: { int: 3, zre: 3 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
  {
    id: "plaszcz_switu_i_cienia",
    name: "Płaszcz Świtu i Cienia",
    slot: "napiersnik",
    icon: "🌗",
    crafted: true,
    description: "Tkanina błogosławiona przez Zakon Światła, podszyta łupem Gildii — chroni ciało i podnosi ducha.",
    bonus: { pancerz: 0.10, cha: 3 },
    cost: { currency: "Kryształy Esencji", amount: 22 },
  },
  {
    id: "ostrze_utopionego_lowcy",
    name: "Ostrze Utopionego Łowcy",
    slot: "prawa_reka",
    icon: "🔱",
    crafted: true,
    description: "Trójząb łowcy Gildii przekuty na nowo w zatopionej kryszcie — nigdy nie wypuszcza zdobyczy.",
    weapon: { name: "Ostrze Utopionego Łowcy", minDmg: 11, maxDmg: 16, range: 1 },
    bonus: { przebicie: 0.06 },
    cost: { currency: "Kryształy Esencji", amount: 24 },
  },
  {
    id: "peleryna_pielgrzyma_glebin",
    name: "Peleryna Pielgrzyma Głębin",
    slot: "lewa_reka",
    icon: "🧣",
    crafted: true,
    description: "Uszyta z relikwii zatopionej krypty i poświęcona w Świątyni — nosi ją tylko ten, kto przeżył obie te głębie.",
    bonus: { pancerz: 0.06, wyt: 3 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
  {
    id: "pierscien_piatej_drogi",
    name: "Pierścień Piątej Drogi",
    slot: "pierscien",
    icon: "💍",
    crafted: true,
    description: "Stopiony z surowców wszystkich pięciu zakątków wokół Aetherionu — nosi ślad każdej drogi, jaką przeszedłeś.",
    bonus: { str: 2, wyt: 2, zre: 2, int: 2, cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 30 },
  },
  // Unikalne łupy bossów — bez pola vendor (nigdy nie trafiają do sklepów),
  // zdobywane wyłącznie za pierwsze pokonanie danego bossa (main.js: grantBossLoot).
  {
    id: "zbroja_pradawnego_streznika",
    name: "Zbroja Pradawnego Strażnika",
    slot: "napiersnik",
    icon: "🗿",
    bossDrop: "boss_kopalnie",
    description: "Odłupana z rdzenia Pradawnego Strażnika Kryształów — wciąż pulsuje echem jego krystalizacji.",
    bonus: { pancerz: 0.22, wyt: 3 },
    cost: { currency: "Kryształy Esencji", amount: 45 },
  },
  {
    id: "naszyjnik_matki_rojowiska",
    name: "Naszyjnik Matki Rojowiska",
    slot: "naszyjnik",
    icon: "🕸️",
    bossDrop: "boss_las",
    description: "Utkany z jej własnej pajęczyny, wciąż lepki od jadu — nosi go tylko ten, kto przeżył jej ukłucie.",
    bonus: { zre: 4, przebicie: 0.06 },
    cost: { currency: "Spaczone Zioła", amount: 45 },
  },
  {
    id: "kusza_zdradzieckiego_lowcy",
    name: "Kusza Zdradzieckiego Łowcy",
    slot: "prawa_reka",
    icon: "🏹",
    bossDrop: "boss_szlak",
    description: "Kusza, którą Zdradziecki Łowca-Mistrz naznaczał każdą ofiarę przed ciosem — wciąż trzyma napięcie.",
    weapon: { name: "Kusza Zdradzieckiego Łowcy", minDmg: 15, maxDmg: 22, range: 6 },
    bonus: { zre: 3, przebicie: 0.05 },
    cost: { currency: "Nagroda Gildii", amount: 45 },
  },
  {
    id: "pierscien_mrocznego_wysysania",
    name: "Pierścień Mrocznego Wysysania",
    slot: "pierscien",
    icon: "🩸",
    bossDrop: "boss_placowka",
    description: "Zdjęty z palca Skorumpowanego Arcykapłana — wciąż ciepły, jakby nieustannie wysysał życie z otoczenia.",
    bonus: { cha: 3, przebicie: 0.05 },
    cost: { currency: "Fiolki Światła", amount: 45 },
  },
  {
    id: "maska_iluzjonisty_doriana",
    name: "Maska Iluzjonisty Doriana",
    slot: "helm",
    icon: "🎭",
    bossDrop: "boss_dorian",
    description: "Maska Doriana Vexa, twórcy tysiąca twarzy — kto ją nosi, zaciera granicę między prawdą a iluzją.",
    bonus: { int: 5, cha: 3 },
    cost: { currency: "Kryształy Esencji", amount: 60 },
  },
  {
    id: "sztylet_egzekutora_rady",
    name: "Sztylet Egzekutora Rady",
    slot: "prawa_reka",
    icon: "🌑",
    bossDrop: "boss_cien_rady",
    description: "Ostrze Cichego Egzekutora Rady — wyważone tak, by nigdy nie chybić i nigdy nie zostać usłyszane.",
    weapon: { name: "Sztylet Egzekutora Rady", minDmg: 14, maxDmg: 20, range: 1 },
    bonus: { zre: 4 },
    cost: { currency: "Nagroda Gildii", amount: 45 },
  },
  {
    id: "szpony_odrzuconego",
    name: "Szpony Odrzuconego",
    slot: "rekawice",
    icon: "🧟",
    bossDrop: "boss_odrzucony",
    description: "Zdeformowane szczątki dłoni pierwszego eksperymentu Doriana — wciąż drgają, jakby pamiętały, czym miały się stać.",
    bonus: { str: 4, przebicie: 0.06 },
    cost: { currency: "Kryształy Esencji", amount: 45 },
  },
  // Unikalne nagrody z misji pobocznych — bez pola vendor, zdobywane wyłącznie
  // po ukończeniu danej misji (main.js: grantSideQuestReward), niezależnie od
  // wyboru dokonanego w jej finale (patrz js/sideQuests.js).
  {
    id: "quest_brenna_mlot",
    name: "Młot Prawdy",
    slot: "prawa_reka",
    icon: "🔨",
    sideQuestDrop: "brenna_krew_w_stali",
    description: "Wykuty przez Brennę z rudy, która ujawniła prawdę o Kopalniach — cięższy niż wygląda, jakby niósł ciężar tego, co odkryłeś.",
    weapon: { name: "Młot Prawdy", minDmg: 16, maxDmg: 24, range: 1 },
    bonus: { str: 3, pancerz: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 40 },
  },
  {
    id: "quest_aldric_amulet",
    name: "Amulet Wyciszonej Wiary",
    slot: "naszyjnik",
    icon: "🕊️",
    sideQuestDrop: "aldric_zaginiona_owieczka",
    description: "Należał niegdyś do brata Tomasza — wciąż ciepły, jakby wciąż się modlił, choć jego wiara zaprowadziła go gdzie indziej.",
    bonus: { wyt: 3, pancerz: 0.06 },
    cost: { currency: "Fiolki Światła", amount: 40 },
  },
  {
    id: "quest_grom_rekawice",
    name: "Rękawice Niezłomnego Mistrza",
    slot: "rekawice",
    icon: "🥊",
    sideQuestDrop: "grom_ostatni_przeciwnik",
    description: "Zdjęte z rąk dawnego mistrza Areny na twoją cześć — wciąż pamiętają setki wygranych starć.",
    bonus: { str: 3, wyt: 2 },
    cost: { currency: "Nagroda Gildii", amount: 40 },
  },
  {
    id: "quest_riven_buty",
    name: "Ciche Buty Przemytnika",
    slot: "buty",
    icon: "🗝️",
    sideQuestDrop: "riven_kontrabanda_rady",
    description: "Noszone podczas dziesiątek nieudokumentowanych „spacerów” przez mur miasta — nie zostawiają śladu i nie robią hałasu.",
    bonus: { zre: 3, przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 40 },
  },

  // Nagrody z osobistych wątków fabularnych towarzyszy (js/companionStory.js,
  // main.js: grantSideQuestReward) — companionStoryDrop mirroruje sideQuestDrop
  // powyżej: żaden kupiec ich nie sprzedaje, trafiają do wspólnego plecaka
  // Gildii po ukończeniu wątku danej specjalizacji, niezależnie od wyboru.
  {
    id: "companion_arcymag_wisior",
    name: "Wisior Cichych Imion",
    slot: "naszyjnik",
    icon: "📖",
    companionStoryDrop: "Arcymag",
    description: "Przetopiony z okładki tomu, który szeptał rzeczy, jakich nikt nie powinien wiedzieć — teraz milczy, ale wciąż ciepły w dotyku.",
    bonus: { int: 3, cha: 1 },
    cost: { currency: "Kryształy Esencji", amount: 40 },
  },
  {
    id: "companion_apostata_pierscien",
    name: "Pieczęć Zerwanego Paktu",
    slot: "pierscien",
    icon: "🖤",
    companionStoryDrop: "Apostata",
    description: "Nosiła ją Apostata od pierwszego dnia długu wobec Otchłani — zimna, nawet gdy reszta dłoni jest rozgrzana.",
    bonus: { int: 2, przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 40 },
  },
  {
    id: "companion_swietlisty_helm",
    name: "Hełm Złamanej Przysięgi",
    slot: "helm",
    icon: "😇",
    companionStoryDrop: "Świetlisty obrońca",
    description: "Noszony od święceń, aż do dnia, gdy sumienie okazało się głośniejsze niż litera prawa Zakonu.",
    bonus: { wyt: 2, pancerz: 0.05 },
    cost: { currency: "Fiolki Światła", amount: 40 },
  },
  {
    id: "companion_mroczny_lancuch",
    name: "Łańcuch Starego Brata Broni",
    slot: "rekawice",
    icon: "🌑",
    companionStoryDrop: "Mroczny rycerz",
    description: "Nosił go rycerz jako przypomnienie o zdradzie — teraz przypomina raczej o tym, jak się z nią rozliczył.",
    bonus: { str: 3, przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 40 },
  },
  {
    id: "companion_najemnik_pieczec",
    name: "Pieczęć Podwójnego Kontraktu",
    slot: "pierscien",
    icon: "🪓",
    companionStoryDrop: "Najemnik bractwa",
    description: "Pozostałość po kontrakcie bez nazwiska — przypomina, że nie każdą zapłatę warto przyjąć.",
    bonus: { zre: 2, przebicie: 0.05 },
    cost: { currency: "Nagroda Gildii", amount: 40 },
  },
  {
    id: "companion_berserk_naszyjnik",
    name: "Naszyjnik Wściekłości Bez Dna",
    slot: "naszyjnik",
    icon: "😡",
    companionStoryDrop: "Berserk",
    description: "Zęby pierwszej bestii, jaką berserk kiedykolwiek pokonał — nosił go, by liczyć powroty z furii, nie ucieczki w nią.",
    bonus: { str: 3, wyt: 1 },
    cost: { currency: "Nagroda Gildii", amount: 40 },
  },
  {
    id: "companion_lowca_buty",
    name: "Ciche Kroki Tropiciela Otchłani",
    slot: "buty",
    icon: "🏹",
    companionStoryDrop: "Łowca",
    description: "Uszyte z futra zwierzyny, która nie powinna istnieć — na tyle ciche, że nawet łowca ledwo słyszy własne kroki.",
    bonus: { zre: 3, przebicie: 0.05 },
    cost: { currency: "Kryształy Esencji", amount: 40 },
  },
  {
    id: "companion_skrytobojca_sztylet",
    name: "Sztylet Umorzonego Długu",
    slot: "lewa_reka",
    icon: "🥷",
    companionStoryDrop: "Skrytobójca",
    description: "Miał zabezpieczyć kontrakt, który w końcu dobiegł końca inaczej, niż planowano — teraz służy komuś, kto wybrał inaczej.",
    weapon: { name: "Sztylet Umorzonego Długu", minDmg: 9, maxDmg: 15, range: 1 },
    bonus: { zre: 2 },
    cost: { currency: "Nagroda Gildii", amount: 40 },
  },
  {
    id: "companion_truciciel_amulet",
    name: "Amulet Podwójnej Recepty",
    slot: "naszyjnik",
    icon: "🧪",
    companionStoryDrop: "Truciciel",
    description: "Fiolka na sznurku, mieszanka trucizny i lekarstwa w jednym — przypomnienie, że wybór wciąż należy do noszącego.",
    bonus: { int: 3, przebicie: 0.05 },
    cost: { currency: "Spaczone Zioła", amount: 40 },
  },
  {
    id: "companion_medyk_kamizelka",
    name: "Kamizelka z Białego Szkła",
    slot: "napiersnik",
    icon: "💊",
    companionStoryDrop: "Medyk",
    description: "Wzmocniona odłamkami fiolek opróżnionych podczas epidemii, którą medyk pamięta liczbami, jakich nie chciał liczyć.",
    bonus: { int: 2, cha: 2, pancerz: 0.04 },
    cost: { currency: "Fiolki Światła", amount: 40 },
  },
];

const EQUIPMENT_SLOTS = [
  { key: "helm", label: "Hełm" },
  { key: "napiersnik", label: "Napierśnik" },
  { key: "rekawice", label: "Rękawice" },
  { key: "spodnie", label: "Spodnie" },
  { key: "buty", label: "Buty" },
  { key: "naszyjnik", label: "Naszyjnik" },
  { key: "pierscien1", label: "Pierścień (1)" },
  { key: "pierscien2", label: "Pierścień (2)" },
  { key: "lewa_reka", label: "Lewa ręka" },
  { key: "prawa_reka", label: "Prawa ręka" },
];

function resolveEquipSlotKey(item, equippedObj) {
  if (item.slot !== "pierscien") return item.slot;
  return equippedObj.pierscien1 ? "pierscien2" : "pierscien1";
}
