const EQUIPMENT_ITEMS = [
  // Napierśnik (obóz)
  {
    id: "zbroja_wyprawowa",
    name: "Zbroja Wyprawowa",
    slot: "napiersnik",
    icon: "🥋",
    vendor: "camp",
    description: "Lekki pancerz łowców Gildii, zszywany ze skóry aberracji.",
    bonus: { pancerz: 0.04 },
    cost: { currency: "Nagroda Gildii", amount: 10 },
  },
  {
    id: "kolczuga_kopalniana",
    name: "Kolczuga Kopalniana",
    slot: "napiersnik",
    icon: "⛓️",
    vendor: "camp",
    description: "Wykuta przez Gildię Rzemieślników z rudy odpornej na spaczenie many.",
    bonus: { pancerz: 0.07 },
    cost: { currency: "Kryształy Esencji", amount: 12 },
  },
  {
    id: "plyta_krysztalowa",
    name: "Płyta Kryształowa",
    slot: "napiersnik",
    icon: "💠",
    vendor: "camp",
    description: "Pancerz inkrustowany esencją — ciężki, ale niemal nieprzebity.",
    bonus: { pancerz: 0.12 },
    cost: { currency: "Kryształy Esencji", amount: 25 },
  },
  // Naszyjnik (obóz)
  {
    id: "amulet_sily",
    name: "Amulet Siły",
    slot: "naszyjnik",
    icon: "💪",
    vendor: "camp",
    description: "Zaklęty przez Zakon Światła talizman wzmacniający ciało.",
    bonus: { str: 3 },
    cost: { currency: "Fiolki Światła", amount: 8 },
  },
  {
    id: "amulet_zrecznosci",
    name: "Amulet Zręczności",
    slot: "naszyjnik",
    icon: "🌀",
    vendor: "camp",
    description: "Wykonany ze spaczonych ziół, przyspiesza ruchy nosiciela.",
    bonus: { zre: 3 },
    cost: { currency: "Spaczone Zioła", amount: 8 },
  },
  {
    id: "amulet_umyslu",
    name: "Amulet Umysłu",
    slot: "naszyjnik",
    icon: "🧠",
    vendor: "camp",
    description: "Kryształ esencji oszlifowany tak, by wzmacniać koncentrację.",
    bonus: { int: 3 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "talizman_przebicia",
    name: "Talizman Przebicia",
    slot: "naszyjnik",
    icon: "🗡️",
    vendor: "camp",
    description: "Nagroda za polowania dla Gildii — osłabia pancerz przeciwnika.",
    bonus: { przebicie: 0.06 },
    cost: { currency: "Nagroda Gildii", amount: 14 },
  },
  // Nowe sloty (obóz)
  {
    id: "kaptur_wedrowca",
    name: "Kaptur Wędrowca",
    slot: "helm",
    icon: "🧢",
    vendor: "camp",
    description: "Prosty kaptur noszony przez każdego, kto wyrusza poza mury.",
    bonus: { pancerz: 0.03 },
    cost: { currency: "Nagroda Gildii", amount: 8 },
  },
  {
    id: "rekawice_skorzane",
    name: "Rękawice Skórzane",
    slot: "rekawice",
    icon: "🧤",
    vendor: "camp",
    description: "Wzmacniają chwyt i pewność ciosu.",
    bonus: { str: 2 },
    cost: { currency: "Spaczone Zioła", amount: 8 },
  },
  {
    id: "spodnie_wedrowca",
    name: "Spodnie Wędrowca",
    slot: "spodnie",
    icon: "👖",
    vendor: "camp",
    description: "Wzmacniane w kolanach — nieocenione na długich wyprawach.",
    bonus: { pancerz: 0.03 },
    cost: { currency: "Kryształy Esencji", amount: 8 },
  },
  {
    id: "buty_wedrowca",
    name: "Buty Wędrowca",
    slot: "buty",
    icon: "🥾",
    vendor: "camp",
    description: "Lekkie podeszwy, które nie zdradzają kroku.",
    bonus: { zre: 2 },
    cost: { currency: "Nagroda Gildii", amount: 8 },
  },
  {
    id: "pierscien_mocy",
    name: "Pierścień Mocy",
    slot: "pierscien",
    icon: "💍",
    vendor: "camp",
    description: "Prosty pierścień z wygrawerowanym symbolem siły.",
    bonus: { str: 2 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "pierscien_zwinnosci",
    name: "Pierścień Zwinności",
    slot: "pierscien",
    icon: "💍",
    vendor: "camp",
    description: "Lekki jak piórko — prawie nie czuć go na palcu.",
    bonus: { zre: 2 },
    cost: { currency: "Spaczone Zioła", amount: 10 },
  },

  // Kuźnia Gildii Rzemieślników
  {
    id: "plyty_gildyjne",
    name: "Płyty Gildyjne",
    slot: "napiersnik",
    icon: "🛡️",
    vendor: "kuznia",
    description: "Najlepsza robota Gildii Rzemieślników — pancerz wart fortuny, kuty na zamówienie samej Rady.",
    bonus: { pancerz: 0.15 },
    cost: { currency: "Kryształy Esencji", amount: 30 },
  },
  {
    id: "obrecz_kowalska",
    name: "Obręcz Kowalska",
    slot: "naszyjnik",
    icon: "⚙️",
    vendor: "kuznia",
    description: "Zaklęta przez kowali Gildii obręcz — hartuje ciało nosiciela jak stal w kuźni.",
    bonus: { wyt: 3 },
    cost: { currency: "Nagroda Gildii", amount: 16 },
  },
  {
    id: "helm_bojowy",
    name: "Hełm Bojowy",
    slot: "helm",
    icon: "⛑️",
    vendor: "kuznia",
    description: "Solidny hełm kuty z myślą o realnym starciu, nie tylko paradzie.",
    bonus: { pancerz: 0.06 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
  {
    id: "rekawice_kolczaste",
    name: "Rękawice Kolczaste",
    slot: "rekawice",
    icon: "🧤",
    vendor: "kuznia",
    description: "Kolce wzmacniające każde uderzenie w słaby punkt pancerza.",
    bonus: { przebicie: 0.05 },
    cost: { currency: "Nagroda Gildii", amount: 14 },
  },
  {
    id: "nogawice_plytowe",
    name: "Nogawice Płytowe",
    slot: "spodnie",
    icon: "👖",
    vendor: "kuznia",
    description: "Ciężkie płyty ochronne — spowalniają, ale chronią żywotne stawy.",
    bonus: { wyt: 3 },
    cost: { currency: "Kryształy Esencji", amount: 18 },
  },
  {
    id: "naramiennik_tarczowy",
    name: "Naramiennik Tarczowy",
    slot: "lewa_reka",
    icon: "🛡️",
    vendor: "kuznia",
    description: "Osłania przedramię przed ciosami, które nie trafiły w korpus.",
    bonus: { pancerz: 0.05 },
    cost: { currency: "Nagroda Gildii", amount: 16 },
  },
  {
    id: "naramiennik_uderzeniowy",
    name: "Naramiennik Uderzeniowy",
    slot: "prawa_reka",
    icon: "👊",
    vendor: "kuznia",
    description: "Wzmocniony staw łokciowy — każdy cios wychodzi mocniejszy.",
    bonus: { str: 3 },
    cost: { currency: "Kryształy Esencji", amount: 16 },
  },
  {
    id: "pierscien_hartu",
    name: "Pierścień Hartu",
    slot: "pierscien",
    icon: "💍",
    vendor: "kuznia",
    description: "Kuty w ogniu esencji — hartuje ciało tak jak stal.",
    bonus: { wyt: 2 },
    cost: { currency: "Nagroda Gildii", amount: 12 },
  },

  // Świątynia Zakonu Światła
  {
    id: "szata_blogoslawiona",
    name: "Szata Błogosławiona",
    slot: "napiersnik",
    icon: "🧥",
    vendor: "swiatynia",
    description: "Tkanina nasączona światłem — chroni duszę niemal tak samo mocno jak ciało.",
    bonus: { pancerz: 0.05, cha: 2 },
    cost: { currency: "Fiolki Światła", amount: 12 },
  },
  {
    id: "relikwiarz",
    name: "Relikwiarz",
    slot: "naszyjnik",
    icon: "🔔",
    vendor: "swiatynia",
    description: "Fragment relikwii Zakonu Światła — wzmacnia więź nosiciela z esencją.",
    bonus: { int: 3 },
    cost: { currency: "Kryształy Esencji", amount: 14 },
  },
  {
    id: "sandaly_pielgrzyma",
    name: "Sandały Pielgrzyma",
    slot: "buty",
    icon: "🩴",
    vendor: "swiatynia",
    description: "Noszone przez wędrownych kapłanów Zakonu — niewygodne, ale budzą zaufanie.",
    bonus: { cha: 2 },
    cost: { currency: "Fiolki Światła", amount: 8 },
  },
  {
    id: "bransoleta_wiary",
    name: "Bransoleta Wiary",
    slot: "lewa_reka",
    icon: "📿",
    vendor: "swiatynia",
    description: "Sznur paciorków otulony słabym, ciepłym światłem.",
    bonus: { int: 2 },
    cost: { currency: "Fiolki Światła", amount: 10 },
  },
  {
    id: "bransoleta_swiatla",
    name: "Bransoleta Światła",
    slot: "prawa_reka",
    icon: "✨",
    vendor: "swiatynia",
    description: "Emanuje słabym blaskiem, który dodaje otuchy w walce.",
    bonus: { cha: 2 },
    cost: { currency: "Fiolki Światła", amount: 10 },
  },
  {
    id: "pierscien_wiedzy",
    name: "Pierścień Wiedzy",
    slot: "pierscien",
    icon: "💍",
    vendor: "swiatynia",
    description: "Noszony niegdyś przez uczonego Zakonu — wciąż pulsuje słabą mądrością.",
    bonus: { int: 2 },
    cost: { currency: "Fiolki Światła", amount: 12 },
  },

  // Czarny Rynek
  {
    id: "przemycony_pancerz",
    name: "Przemycony Pancerz Aberracji",
    slot: "napiersnik",
    icon: "🦴",
    vendor: "czarny_rynek",
    description: "Zszyty ze skóry aberracji, sprzedany przez kogoś, kto nie miał prawa go posiadać.",
    bonus: { pancerz: 0.09, przebicie: 0.05 },
    cost: { currency: "Nagroda Gildii", amount: 22 },
  },
  {
    id: "sygnet_rady",
    name: "Kradziony Sygnet Rady",
    slot: "pierscien",
    icon: "💍",
    vendor: "czarny_rynek",
    description: "Sygnet z herbem jednego z Radnych — ktoś zapłaci fortunę, żeby go odzyskać, ale na razie jest Twój.",
    bonus: { str: 2, cha: 2 },
    cost: { currency: "Kryształy Esencji", amount: 20 },
  },
];

const EQUIPMENT_SLOTS = [
  { key: "helm", label: "Hełm" },
  { key: "napiersnik", label: "Napierśnik" },
  { key: "rekawice", label: "Rękawice" },
  { key: "spodnie", label: "Spodnie" },
  { key: "buty", label: "Buty" },
  { key: "naszyjnik", label: "Naszyjnik" },
  { key: "pierscien1", label: "Pierścień (1)" },
  { key: "pierscien2", label: "Pierścień (2)" },
  { key: "lewa_reka", label: "Lewa ręka" },
  { key: "prawa_reka", label: "Prawa ręka" },
];

function resolveEquipSlotKey(item) {
  if (item.slot !== "pierscien") return item.slot;
  return equipped.pierscien1 ? "pierscien2" : "pierscien1";
}
