const EQUIPMENT_ITEMS = [
  {
    id: "zbroja_wyprawowa",
    name: "Zbroja Wyprawowa",
    slot: "zbroja",
    icon: "🥋",
    description: "Lekki pancerz łowców Gildii, zszywany ze skóry aberracji.",
    bonus: { pancerz: 0.04 },
    cost: { currency: "Nagroda Gildii", amount: 10 },
  },
  {
    id: "kolczuga_kopalniana",
    name: "Kolczuga Kopalniana",
    slot: "zbroja",
    icon: "⛓️",
    description: "Wykuta przez Gildię Rzemieślników z rudy odpornej na spaczenie many.",
    bonus: { pancerz: 0.07 },
    cost: { currency: "Kryształy Esencji", amount: 12 },
  },
  {
    id: "plyta_krysztalowa",
    name: "Płyta Kryształowa",
    slot: "zbroja",
    icon: "💠",
    description: "Pancerz inkrustowany esencją — ciężki, ale niemal nieprzebity.",
    bonus: { pancerz: 0.12 },
    cost: { currency: "Kryształy Esencji", amount: 25 },
  },
  {
    id: "amulet_sily",
    name: "Amulet Siły",
    slot: "amulet",
    icon: "💪",
    description: "Zaklęty przez Zakon Światła talizman wzmacniający ciało.",
    bonus: { str: 3 },
    cost: { currency: "Fiolki Światła", amount: 8 },
  },
  {
    id: "amulet_zrecznosci",
    name: "Amulet Zręczności",
    slot: "amulet",
    icon: "🌀",
    description: "Wykonany ze spaczonych ziół, przyspiesza ruchy nosiciela.",
    bonus: { zre: 3 },
    cost: { currency: "Spaczone Zioła", amount: 8 },
  },
  {
    id: "amulet_umyslu",
    name: "Amulet Umysłu",
    slot: "amulet",
    icon: "🧠",
    description: "Kryształ esencji oszlifowany tak, by wzmacniać koncentrację.",
    bonus: { int: 3 },
    cost: { currency: "Kryształy Esencji", amount: 10 },
  },
  {
    id: "talizman_przebicia",
    name: "Talizman Przebicia",
    slot: "amulet",
    icon: "🗡️",
    description: "Nagroda za polowania dla Gildii — osłabia pancerz przeciwnika.",
    bonus: { przebicie: 0.06 },
    cost: { currency: "Nagroda Gildii", amount: 14 },
  },
];

const EQUIPMENT_SLOTS = [
  { key: "zbroja", label: "Zbroja" },
  { key: "amulet", label: "Amulet" },
];
