const LOCATIONS = [
  {
    key: "kopalnie",
    name: "Kopalnie Esencji",
    icon: "⛏️",
    description: "Podziemne szyby, gdzie niewolnicy wydobywają pulsujące kryształy. Promieniowanie esencji mutowało niejednego górnika w coś, co dawno przestało być człowiekiem.",
    enemyKeys: ["gornik", "aberracja", "kopacz", "pelzacz", "nadzorca", "pijawka", "kolos", "rdzawyautomat", "iskiernikesencji", "skalnysluga"],
    obstacleBias: "rock",
    resource: { name: "Kryształy Esencji", icon: "💎", min: 8, max: 16 },
    bossKey: "boss_kopalnie",
  },
  {
    key: "las",
    name: "Skażony Las",
    icon: "🌲",
    description: "Poza murami Aetherionu powietrze trzeszczy od niestabilnej many. Fauna tych lasów dawno przestała być fauną — aberracje czają się między drzewami.",
    enemyKeys: ["aberracja", "gornik", "wilk", "konstrukt", "szarancza", "pomiot", "traper", "pajeczydozorca", "spaczonymotyl", "fungalnypomiot"],
    obstacleBias: "tree",
    resource: { name: "Spaczone Zioła", icon: "🌿", min: 6, max: 12 },
    bossKey: "boss_las",
  },
  {
    key: "szlak",
    name: "Szlak Gildii",
    icon: "🗺️",
    description: "Trasa patrolowana przez Gildię Poszukiwaczy Przygód — brutalnych łowców nagród, lojalnych wobec Rady za ochłapy esencji.",
    enemyKeys: ["lowca", "zwiadowca", "egzekutor", "tropiciel", "strzelec", "kapitan", "tarczownikgildii", "jezdziecgildii", "sabotazysta"],
    obstacleBias: "lake",
    resource: { name: "Nagroda Gildii", icon: "🪙", min: 10, max: 20 },
    bossKey: "boss_szlak",
  },
  {
    key: "placowka",
    name: "Placówka Zakonu Światła",
    icon: "⛪",
    description: "Skromna misja Zakonu Światła, gdzie adepci „leczą” niewolników słabymi czarami — wystarczająco, by mogli wrócić do kopania.",
    enemyKeys: ["adept", "nowicjusz", "egzekutorwiary", "inkwizytor", "straznik", "kaplanka", "kustoszrelikwii", "flagellant", "straznikllancuchow", "inkwizycyjnypodpalacz"],
    obstacleBias: "rock",
    resource: { name: "Fiolki Światła", icon: "🧴", min: 5, max: 10 },
    bossKey: "boss_placowka",
  },
  {
    key: "krypty",
    name: "Zatopione Krypty",
    icon: "⚰️",
    description: "Podziemne grobowce Rady sprzed Wojny Esencji, dawno zatopione przez pękniętą żyłę wodną. W mrocznej wodzie kołyszą się ciała, które nigdy nie zaznały spokoju — a coś w najgłębszej krypcie wciąż rządzi.",
    enemyKeys: ["utopiony", "widmokrypty", "kostotwor", "mackaglebin", "straznikkrypty", "zjawabagienna", "nekromantaodrzuconych"],
    obstacleBias: "lake",
    resource: { name: "Zatopione Relikwie", icon: "⚱️", min: 7, max: 14 },
    bossKey: "boss_krypty",
  },
];

const ARENA_LOCATION = {
  key: "arena",
  name: "Arena Krwi",
  icon: "⚔️",
  description: "Prowizoryczna arena na tyłach miasta, gdzie najemnicy ćwiczą się na sobie nawzajem, zanim wyruszą po prawdziwą zdobycz.",
  enemyKeys: null,
  obstacleBias: null,
  resource: { name: "Nagroda Gildii", icon: "🪙", min: 4, max: 8 },
};
