const TUTORIAL_TABS = [
  { key: "basics", label: "Podstawy" },
  { key: "creation", label: "Tworzenie postaci" },
  { key: "camp", label: "Obóz i wyprawy" },
  { key: "combat", label: "Walka" },
  { key: "progression", label: "Ekwipunek i rozwój" },
  { key: "saves", label: "Zapisy" },
];

const TUTORIAL_DATA = {
  basics: {
    icon: "🎯",
    title: "Podstawy",
    paragraphs: [
      "Raj to taktyczna gra turowa osadzona w mrocznym świecie Aetherionu — walczysz na heksagonalnej siatce, gdzie pozycja, zasięg broni i teren decydują o wyniku starcia.",
      "Pętla rozgrywki wygląda tak: w obozie tworzysz i rozwijasz postać, wyruszasz na wyprawę do wybranej lokacji, walczysz z przeciwnikami, a po walce wracasz do obozu z surowcami i doświadczeniem, które wydajesz na ekwipunek i punkty statystyk przed kolejną wyprawą.",
    ],
  },
  creation: {
    icon: "🧝",
    title: "Tworzenie postaci",
    paragraphs: [
      "Przy „Nowa gra” najpierw tworzysz postać: wpisujesz imię, wybierasz płeć, a następnie klasę i specjalizację — kliknięcie ikony klasy centruje ją i powiększa, a poniżej pojawia się opis wybranej specjalizacji wraz z jej bronią i umiejętnością.",
      "Masz do rozdania 10 punktów statystyk (STR/WYT/ZRE/INT/CHA) na bazie wybranej specjalizacji — dodatkowe punkty do WYT i STR zwiększają też HP. Klasa i imię są ustalane raz na całą grę — nie da się ich zmienić w trakcie walki.",
      "Po zatwierdzeniu postaci zobaczysz krótki prolog — osobną historię dla każdej z 5 klas, wyjaśniającą, skąd Twoja postać się wzięła i dlaczego trafia do Gildii Poszukiwaczy Przygód jako „nowy rekrut”. Przycisk „Dalej” przechodzi do kolejnego fragmentu, a „Pomiń prolog” od razu przenosi do obozu, jeśli wolisz przejść od razu do gry.",
    ],
  },
  camp: {
    icon: "🏕️",
    title: "Obóz i wyprawy",
    paragraphs: [
      "Obóz Gildii to Twoja baza — stąd wyruszasz na wyprawy, przeglądasz ekwipunek i postać, oraz zaglądasz do kodeksu świata. Po zakończonej walce (zwycięskiej lub nie) wracasz właśnie tutaj.",
      "„📋 Tablica zadań” pokazuje proste cele Gildii wraz z paskiem postępu: pokonaj 5 przeciwników, osiągnij 3. poziom i odkryj 3 różnych przeciwników w Bestiariuszu. Każde zadanie da się odebrać tylko raz, a nagroda to zawsze porcja jednego z surowców.",
      "„🗡️ Kampania” to główny wątek fabularny — Twoja osobista zemsta na zdrajcy Dorianie Vex. Siedem rozdziałów odblokowuje się jeden po drugim: pierwsze cztery to unikalne, samotne walki z bossami czterech lokacji Twojego świata (bez przechodzenia przez loch); piąty i szósty to zwrot akcji, gdy Rada wysyła za Tobą Cichego Egzekutora, a trop po nim prowadzi do zapomnianego laboratorium Doriana i jego pierwszego, odrzuconego eksperymentu; siódmy to finałowa konfrontacja z Dorianem w Wieży Rady — gdy go odblokujesz, sam Dorian skomentuje na tablicy kampanii, jak głęboko poddałeś się spaczeniu i jak rozstrzygałeś swoje wybory w mieście i wobec towarzyszy, zanim jeszcze do niego dotrzesz. Każdy rozdział ma własny wstęp i zakończenie fabularne oraz nagrodę w surowcach po zwycięstwie.",
      "Pokonanie Doriana w piątym rozdziale nie kończy się cichym powrotem do obozu — od razu widzisz pełny epilog: wspólne zakończenie fabuły, osobistą refleksję zależną od Twojej klasy (nawiązującą wprost do prologu, którym zaczynałeś grę), krótką kodę zależną od tego, jak głęboko poddałeś się spaczeniu many w trakcie całej wyprawy, oraz — jeśli ukończyłeś choć jedną misję poboczną NPC albo osobisty wątek towarzysza — ostatnie podsumowanie tego, jak często wybierałeś uczciwość i lojalność, a jak często mrok i milczenie.",
      "„👥 Drużyna” pokazuje Twoich towarzyszy (maks. 3, zawsze innej klasy niż Twoja). W dwóch losowych miejscach w mieście Aetherion czekają potencjalni rekruci — każdy ma własny, osobisty powód, dla którego chce Cię najpierw wypróbować: jedni każą pokonać określoną liczbę przeciwników, inni żądają osiągnięcia konkretnego poziomu doświadczenia, odkrycia kilku stworzeń w Bestiariuszu albo zebrania określonej ilości jednego z surowców. Pasek postępu i opis zadania pokazują dokładnie, o co chodzi danemu rekrutowi. Po osiągnięciu celu przycisk zmienia się w „Porozmawiaj” — otwiera krótką scenę dialogową: powitanie, nieoczekiwana komplikacja i jej rozwiązanie wspólnym wysiłkiem, a na koniec przycisk „Przyjmij do drużyny” faktycznie werbuje rekruta (jeśli jest miejsce). Rekruci zmieniają się przy każdej nowej wyprawie, więc jeśli kogoś przegapisz, pojawi się ktoś inny. W walce towarzysze poruszają się w stronę najbliższego wroga i automatycznie korzystają ze swoich dwóch startowych czarów specjalizacji oraz odblokowanych aktywnych umiejętności z własnego drzewka, gdy są gotowe (odnowione) i cel jest w ich zasięgu — dopiero bez gotowej zdolności atakują zwykłą bronią. Przeciwnicy też mogą wybrać ich jako cel zamiast Ciebie. Przycisk „🎒 Ekwipunek” przy każdym towarzyszu otwiera jego arkusz: sloty ekwipunku (ekwipunek to jedna wspólna pula Gildii, więc dany przedmiot noszą naraz Ty albo jeden z towarzyszy, nigdy dwoje na raz), własne punkty statystyk do rozdania co poziom (dokładnie jak u Ciebie) oraz przycisk „🌟 Umiejętności” otwierający jego własne drzewko talentów specjalizacji — z tymi samymi regułami co Twoje (ranga II gałęzi wymaga rangi I w tej samej gałęzi) i osobnym przyciskiem „🔄 Przebuduj” zwracającym jego wydane punkty za Kryształy Esencji. Niektóre pary specjalizacji w drużynie mają też ze sobą chemię — na początku niektórych walk usłyszysz krótką wymianę zdań między dwoma konkretnymi towarzyszami w logu walki (np. paladyn kontra mroczny rycerz, łowczyni kontra truciciel). Każda taka rozmowa pojawia się co najwyżej raz na całą grę, więc warto próbować różnych składów drużyny.",
      "Każdy towarzysz kryje też własny, osobisty wątek fabularny, oddzielny od jednorazowego zadania rekrutacyjnego — odblokowuje się od razu po dołączeniu do drużyny i widać go w jego arkuszu pod „📖 Historia towarzysza”. Działa tak samo jak wieloetapowe misje poboczne w mieście: dialog wprowadzający prowadzi do prawdziwego celu w świecie (pokonaj kolejnych przeciwników, osiągnij poziom, odkryj przeciwników w Bestiariuszu, zbierz surowiec albo zanurz się w spaczeniu), a po powrocie kończy się wyborem z dwiema opcjami o realnie różnych konsekwencjach — jedna zwykle daje temu towarzyszowi trwały, dodatkowy punkt do wybranej statystyki, druga pogłębia Twoje własne spaczenie many. Niezależnie od wyboru dostajesz ten sam unikalny przedmiot, niedostępny u żadnego kupca. Podobnie jak misje w mieście, wątek można zamknąć w dowolnym momencie i wrócić do niego później — postęp zapisuje się razem z resztą stanu towarzysza.",
      "Każda lokacja wyprawy ma inną pulę przeciwników, dominujący typ terenu (skały/drzewa/woda) oraz inny surowiec przyznawany za zwycięstwo — warto odwiedzać różne miejsca, żeby zebrać komplet zasobów potrzebnych u kupca.",
      "Po wybraniu lokacji nie trafiasz od razu do walki — najpierw eksplorujesz prawdziwą mapę lochu złożoną z heksów: wąskie, kręte korytarze łączą większe, otwarte komnaty. Klikasz dowolne odkryte pole, a Twoja postać sama tam dochodzi (mgła wojny odsłania kolejne fragmenty mapy w miarę zwiedzania). Po drodze — zarówno w korytarzach, jak i w komnatach — czekają: zasadzki (⚔️), które od razu wciągają Cię w prawdziwą walkę taktyczną, po której wracasz na mapę lochu (przycisk „↩️ Wróć do lochu” zamiast „🏕️ Wróć do obozu”), oraz interaktywne obiekty do zbadania — Cichy zaułek możesz przeszukać (szansa na drobny łup, bez ryzyka) albo iść dalej, Pułapkę rozbroić (łup przy sukcesie, obrażenia przy porażce) albo bezpiecznie ominąć, Znalezisko zbadać dokładnie (większa nagroda, ale ryzyko pułapki) albo zabrać szybko i bezpiecznie, a Zapomniany ołtarz przyjmie ofiarę z Twojego zdrowia w zamian za tymczasowe wzmocnienie pancerza na nadchodzącą walkę. Do tego trafisz też na Zapieczętowaną skrzynię, którą możesz spróbować wyważyć siłą (im wyższa Twoja Siła, tym większa szansa na łup — porażka kosztuje HP) albo zostawić zamkniętą, Spaczony posąg, którego dotknięcie leczy część zgromadzonych obrażeń kosztem trwałego wzrostu spaczenia, oraz Rannego wędrowca, którego opatrzenie zawsze nagradza losową miksturą. Jedna lub dwie boczne, ślepo zakończone kieszenie na mapie czasem kryją tajemniczą „❓ Nieznaną głębię” — rzadką szansę na starcie z bossem lokacji, którego możesz wyzwać albo wycofać się w milczeniu. Dotarcie do komnaty wyjścia (🚪) uruchamia właściwą walkę o tę lokację, tak jak dotychczas.",
      "Obrażenia z nieudanych wyborów przechodzą na Twoje HP w nadchodzącej walce, więc ryzykowne opcje naprawdę coś kosztują, jeśli się nie powiedzie.",
      "Bossowie (napotkani w „❓ Nieznanej głębi” lochu albo w kampanii fabularnej) to unikalni, dużo silniejsi przeciwnicy z własną zdolnością specjalną, właściwi dla danej lokacji. Poza potrójną nagrodą surowców, pierwsze pokonanie danego bossa w tej grze przynosi też jego unikalny, niedostępny u żadnego kupca przedmiot ekwipunku — trafia od razu do plecaka.",
    ],
  },
  combat: {
    icon: "⚔️",
    title: "Walka",
    paragraphs: [
      "Na początku walki rozstawiasz postać, klikając dowolne wolne pole w swojej strefie (trzy lewe kolumny) — przeciwnicy rozstawiają się automatycznie.",
      "Każda tura to pula akcji (zależna od ZRE) — ruch o jedno pole i atak/umiejętność/zmiana broni kosztują po jednej akcji. Atak wymaga, żeby cel był w zasięgu broni; jeśli nie jest, podejdź bliżej albo kliknij swój token, żeby otworzyć menu zmiany broni, rzucenia jednej z dwóch umiejętności specjalizacji lub wypicia mikstury.",
      "Każda specjalizacja ma dwie unikalne umiejętności, nie tylko zwykły atak na dystans — do wyboru: odpryski ognia na sąsiednie cele, osłabienie pancerza wroga, samoleczenie, wysysanie HP z celu, ignorowanie pancerza, chwilowe wzmocnienie statystyki, gwarantowane trafienie krytyczne albo trucizna zadająca obrażenia co turę (także w formie trującego oparu na kilka celów naraz). Obie umiejętności mają osobne odnowienie na kilka tur — czas odnowienia widać w menu i w opisie specjalizacji przy tworzeniu postaci.",
      "Obrażenia liczone są z dwóch kostek: K6 trafia w część ciała (nogi/ręce/brzuch/klatka/głowa — głowa to krytyk x2), a K20 daje mnożnik obrażeń. Sojusznik stojący dokładnie po przeciwnej stronie celu daje +15% obrażeń (flankowanie), a przeszkoda na linii strzału przy ataku dystansowym daje celowi -25% obrażeń (osłona).",
      "Walki są brutalne — nie ma auto-leczenia w trakcie starcia, więc każde trafienie się liczy. Jedynym ratunkiem są mikstury: kliknij swój token, żeby otworzyć menu, i wybierz „🧪 Mikstury” — otworzy się plecak z eliksirami kupionymi u zielarza w obozie. Wypicie kosztuje jedną akcję, tak jak atak, ruch czy rzucenie czaru.",
      "Raz rozpoczętego starcia nie da się porzucić — przycisk „🏕️ Wróć do obozu” (albo, po zasadzce w lochu, „↩️ Wróć do lochu”) jest zablokowany, dopóki walka trwa, i odblokowuje się dopiero po jej zakończeniu, zwycięstwem albo porażką. Porażka też ma cenę: jeśli zginiesz, tracisz w odwrocie część zapasów zasobu zbieranego w tej lokacji.",
      "W menu tokenu znajdziesz też „🧬 Mutuj się” — poddajesz swoje ciało spaczeniu many w zamian za +6 STR i +6 WYT do końca walki (koszt: jedna akcja, własne odnowienie). Cena jest realna: każde użycie trwale podnosi Twoje Spaczenie (widoczne w panelu walki i arkuszu postaci). Powyżej 20% Spaczenia każdy atak i każde zaklęcie niosą rosnące ryzyko obłędu — zamiast wroga możesz zaatakować własnego towarzysza (a bez towarzyszy obrócić furię przeciw sobie). Świątynia Zakonu Światła w mieście oferuje osobne „Oczyszczenie Spaczenia”, które zeruje licznik za surowce — ale nie cofa już zdobytej mocy. Ukryty w mieście 🌀 Kult Spaczenia oferuje dokładnie odwrotną usługę: „Rytuał Wchłonięcia” za surowce świadomie podnosi Spaczenie, ale też trwale wzmacnia mutację (tak jak „🍖 Pożryj szczątki” w walce) — działa nawet poza starciem i nie da się go cofnąć Oczyszczeniem.",
      "Mutację można rozwijać w walce: gdy pokonany wróg jest wyraźnie spaczony (zmutowani mieszkańcy Kopalni i Lasu, w tym ich bossowie), a jego zwłoki leżą tuż obok Ciebie, w menu tokenu pojawi się „🍖 Pożryj szczątki”. To osobna akcja (koszt: jedna) — leczy Cię o kawałek maksymalnego HP i podnosi Spaczenie mniej niż „Mutuj się”, ale za to trwale: co 3 pożarte zwłoki (do limitu) „Mutuj się” daje coraz większy bonus do STR/WYT na resztę Twojej gry, nawet po Oczyszczeniu Spaczenia.",
      "Przycisk „🧊 Widok 3D” przełącza planszę w widok trójwymiarowy — to ta sama walka, tylko inaczej pokazana. Brązowe wzniesienia to skały, wysokie zielone bloki to drzewa, niebieskie pola to jeziora; złota kula to Ty, czerwone stożki to przeciwnicy. Klikasz pola tak samo jak w 2D, a myszą obracasz kamerę (przeciągnięcie) i przybliżasz (przewinięcie). „🗺️ Widok 2D” wraca do klasycznej planszy.",
    ],
  },
  progression: {
    icon: "🎒",
    title: "Ekwipunek i rozwój",
    paragraphs: [
      "Zwycięstwo przynosi surowiec danej lokacji oraz punkty doświadczenia (PD) — im mocniejsi pokonani przeciwnicy, tym więcej PD. Kolejne poziomy wymagają coraz więcej PD i dają +3 punkty statystyk oraz +1 punkt umiejętności do rozdania w obozie.",
      "„🌟 Umiejętności” (dostępne z obozu) ma dwie zakładki. „🌟 Specjalizacja” to drzewko talentów Twojej klasy, wzorowane na Dragon Age: Origins — trzy gałęzie po cztery rangi każda. Węzły bywają bierne (stały bonus do statystyk), aktywowane (nowa zdolność bojowa z własnym odnowieniem, dochodząca do dwóch startowych czarów w menu tokenu) albo podtrzymywane (aktywowana zdolność o dłuższym działaniu i odnowieniu). Kliknij węzeł, żeby zobaczyć jego pełny opis w bocznym panelu — ranga II danej gałęzi wymaga odblokowanej rangi I w tej samej gałęzi, aż po szczytową rangę IV.",
      "„🧬 Mutacja” to druga zakładka — jedna wspólna, czterorangowa ścieżka dostępna dla każdej klasy, tematycznie związana ze spaczeniem i pożeraniem szczątków (patrz niżej). Miesza bierne wzmocnienia ciała z coraz potężniejszymi, potwornymi atakami i wydaje te same punkty umiejętności co drzewko specjalizacji — obie zakładki konkurują o tę samą, wspólną pulę. „Oczyszczenie Wspomnień” w Świątyni zwraca wydane punkty z obu zakładek naraz, nie tylko statystyk.",
      "Wszystkie sklepy w Aetherionu (ekwipunek, mikstury, ulepszenia, Oczyszczenie Wspomnień, Rytuał Wchłonięcia) przyjmują wyłącznie 💎 Kryształy Esencji. Pozostałe surowce lokacji — 🌿 Spaczone Zioła, 🪙 Nagroda Gildii, 🧴 Fiolki Światła, ⚱️ Zatopione Relikwie — nie kupują niczego same z siebie, ale są potrzebne do zleceń NPC, zakładów w Tawernie i wytwarzania w Kuźni, więc wciąż warto odwiedzać wszystkie lokacje.",
      "W „🎒 Ekwipunek i postać” (dostępnym z obozu) widzisz pełne statystyki, zakładasz zbroje i amulety kupione u kupca obozowego za zebrane surowce, oraz rozdzielasz niewydane punkty statystyk. Tam samo znajdziesz też zielarza — sprzedaje mikstury lecznicze i eliksiry chwilowo wzmacniające SIŁ/WYT/pancerz, które trafiają do plecaka i czekają na użycie w trakcie walki.",
      "Sloty Lewa ręka/Prawa ręka mogą trzymać nie tylko naramienniki i bransolety, ale też prawdziwe bronie sprzedawane u różnych kupców — po założeniu dołączają do puli broni dostępnej przez „🔁 Zmień broń” w menu tokenu, więc możesz mieć więcej niż dwie opcje ataku o różnym zasięgu i obrażeniach.",
      "„🏙️ Miasto Aetherion” (dostępne z obozu) kryje kilka budynków, każdy z własnym sklepem i usługą: ⚒️ Kuźnia Gildii Rzemieślników sprzeda unikalny ekwipunek, ulepszy każdy przedmiot, który już posiadasz (do 3 poziomów, coraz droższych, każdy dodaje +25% do jego bonusu), a w sekcji „🛠️ Wytwarzanie” pozwala połączyć surowce z różnych lokacji naraz w unikalny przedmiot, niedostępny u żadnego kupca. ⛪ Świątynia Zakonu Światła oferuje własny towar oraz „Oczyszczenie Wspomnień” — za Kryształy Esencji zwraca wszystkie wydane punkty statystyk do ponownego rozdania, jeśli chcesz przebudować postać.",
      "⚔️ Arena Krwi pozwala stoczyć natychmiastową walkę z losowym przeciwnikiem bez wyprawy i lochu — mniejsza nagroda, ale zero ryzyka po drodze i można wracać w kółko. 🏴 Czarny Rynek kupi z powrotem niepotrzebny ekwipunek i mikstury (za połowę pierwotnej ceny) i sprzedaje kilka unikalnych, przemyconych przedmiotów. 🍺 Tawerna Pod Pękniętym Kryształem oferuje grę w kości — stawiasz dowolny posiadany surowiec, a rzut K20 decyduje: 1-8 przegrywasz zakład, 9-14 remis, 15-20 podwajasz stawkę. 🌀 Kult Spaczenia, ukryta sekta wielbiąca mutację jako dar, oferuje „Rytuał Wchłonięcia” — świadome zwiększenie Spaczenia za surowce w zamian za trwałe wzmocnienie mutacji.",
      "Każde z sześciu miejsc w mieście ma swojego stałego bywalca — kliknij „💬 Zapytaj o coś”, żeby usłyszeć jedną z kilku losowych kwestii (plotki, komentarze o świecie, czasem coś więcej niż zwykła gadka). Każdy z nich ma też własne jednorazowe zlecenie z paskiem postępu i nagrodą w surowcach, niezależne od Tablicy zadań Gildii: poziom doświadczenia, liczba pokonanych przeciwników, odkryte stworzenia w Bestiariuszu albo określona ilość jednego z surowców.",
      "Czterech bywalców (Brenna z Kuźni, brat Aldric ze Świątyni, Grom z Areny i Riven z Czarnego Rynku) kryje też coś więcej — wieloetapową misję poboczną, osobną od ich zwykłego zlecenia. Taka misja zaczyna się dialogiem, prowadzi do prawdziwego celu do wykonania w świecie (np. pokonaj kolejnych przeciwników, zejdź głębiej w spaczenie, osiągnij poziom albo zbierz surowiec), a po powrocie do NPC kończy się wyborem z dwiema opcjami o realnie różnych konsekwencjach — jedna zwykle podnosi Twoją reputację w tym miejscu, druga pogłębia spaczenie many, niezależnie od tego, którą wybierzesz, dostajesz ten sam unikalny przedmiot, niedostępny u żadnego kupca. Misja pojawia się w panelu NPC dopiero, gdy spełnisz jej próg wejścia, i można ją zamknąć w dowolnym momencie i wrócić do niej później — postęp zapisuje się automatycznie.",
      "Każde miejsce w mieście śledzi też Twoją „🤝 Reputację” — rośnie ona o punkt za każdy zakup w tamtejszym sklepie, o punkt za wygraną w Arenie czy grę w Tawernie, o punkt za sprzedaż na Czarnym Rynku, a o 5 punktów za wykonanie tamtejszego zlecenia. Każdy punkt reputacji obniża ceny w danym sklepie o 1% (do maksymalnie 20% rabatu) — im częściej wracasz w jedno miejsce, tym taniej tam kupujesz.",
      "Surowce, ekwipunek i mikstury zostają na koncie nawet po rozpoczęciu nowej gry — resetuje się tylko poziom, doświadczenie i punkty statystyk aktualnej postaci.",
      "Przeciwnicy skalują się razem z Tobą — im wyższy Twój poziom, tym więcej mają HP, STR, WYT, pancerza i przebicia, więc wyprawy pozostają wyzwaniem nawet gdy postać mocno się rozwinie.",
    ],
  },
  saves: {
    icon: "💾",
    title: "Zapisy",
    paragraphs: [
      "Gra zapisuje stan automatycznie po każdej akcji, więc możesz spokojnie zamknąć kartę w dowolnym momencie.",
      "„Wznów” w menu głównym błyskawicznie wraca do miejsca, w którym skończyłeś. „Wczytaj grę” robi to samo, ale najpierw pokazuje podsumowanie zapisu do potwierdzenia. „Nowa gra” zaczyna od tworzenia nowej postaci (zasoby i ekwipunek zostają). „Wyczyść cały postęp” w Ustawieniach kasuje wszystko bezpowrotnie.",
    ],
  },
};
